#eureka服务端口号
server:
  port: 8761
  #应用名称会在Eureka中作为服务名称
spring:
  application:
    name: lane-cloud-eureka-server
# eureka 客户端配置（和Server交互），Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: www.abc.com  # 当前eureka实例的主机名
  client:
    service-url:
      # 配置客户端所交互的Eureka Server的地址（Eureka Server集群中每一个Server其实相对于其它Server来说都是Client）
      # 集群模式下，defaultZone应该指向其它Eureka Server，如果有更多其它Server实例，逗号拼接即可
      defaultZone: http://www.def.com:8762/eureka
      #defaultZone: http://localhost:8761/eureka
    register-with-eureka: true  # 集群模式下可以改成true,当前自己就是server不需要注册自己false
    fetch-registry: true # 集群模式下可以改成true，单机不需要从服务获取注册信息false
